### ISSUE TITLE
Name function in base strategy is pure when it should be view

### ISSUE THREAD

**Issue by Grandthrax** [iearn-finance/yearn-vaults#104]
In base strategy is: function name() external virtual pure returns (string memory);

It should be view and not pure. As pure we can't read from state so can't store a name.

**Comment by dmolina79** [comment]
The idea is to always return a hardcoded name so no need to store it.

` return "TestStrategy";`

**Comment by Grandthrax** [comment]
Some strategies are the same but just different want. So would like to set name in constructor. for instance leveraged dai and leveraged usdc comp farm are exactly the same. but I want to set the name to show want

**Comment by fubuloubu** [comment]
I see no problems in doing this

**Comment by fubuloubu** [comment]
Fixed in #144
