### ISSUE TITLE
Set Deposit Limit to 0 on deployment

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#121]
Currently, the deposits are unlimited on deployment. This is potentially problematic, as we shouldn't allow Vaults to be immediately available during the setup/configuration phase. Due to how deployments are handled, it would be safer to have to set this manually in order to "open up" the Vault for deposits once deployed to mainnet, which can use multicall in order to set all the parameters needed at once, including Strategy approvals, Guest List, etc.

**Comment by fubuloubu** [comment]
Note: the biggest change here will be updating all the test cases

**Comment by dmolina79** [comment]
With the new registry proposal is this still a change needed on the vault, or we can handle on the template factory initialize @fubuloubu ?

**Comment by fubuloubu** [comment]
@dmolina79 it's in the constructor/initialize function, which I didn't change, so it would probably be worth doing separately

**Comment by hrharder** [comment]
willing to take a stab if this hasn't been picked up by anyone else yet -- understand the tests will need changes as well, but feel confident I should be able to sort it out

in `Vault.vy`, the only change would be changing

```py
self.depositLimit = MAX_UINT256  # Start unlimited
log UpdateDepositLimit(MAX_UINT256)
```

to

```py
self.depositLimit = 0  # Start with no deposits allowed (must be set after deployment)
log UpdateDepositLimit(0)
```

correct (ignoring pseudocode, assuming some types will need to be converted or whatever -- still figuring out the type system)?

**Comment by fubuloubu** [comment]
@hrharder you can just remove that line entirely. The EVM assumes un-set values are 0 by default. Maybe leave your comment there at the end for reference ("Start with no deposits allowed (must be set after deployment)")

**Comment by hrharder** [comment]
PR up
