### ISSUE TITLE
Add Events for parameter changes in Vault

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#128]
Parameter changes would be very helpful to have the history logged so they can be searched in history

**Comment by hrharder** [comment]
@fubuloubu has anyone agreed to tackle this yet? if not, i'd be willing to give it a go

primarily experienced with golang and python, but have worked extensively with contracts/solidity so feel like I should be able to do this pretty easily by this weekend if its helpful

**Comment by fubuloubu** [comment]
@hrharder yes, you can give it a go. The following will serve as an aide. Please add events like these in Vault.vy for governance upgrade, strategy parameter updates (rate limit, debt limit, migration, etc.) and vault parameter upgrades (deposit limit, guest list, etc.) Thanks!

https://github.com/iearn-finance/yearn-vaults/pull/124/files#diff-096c8e9d951cde1c28070e4ef10658a45c746777741fbefd68749a5ba3fe6f30R54-R55

**Comment by hrharder** [comment]
great! 

you have a preference for one/a few types of events (e.g. `ParameterUpdate`) with fields `parameterName`, or many events? (e.g. `UpdateRateLimit`, `UpdateDebtLimit`, etc.)? Personally tend to prefer more granular events, but LMK

**Comment by fubuloubu** [comment]
granular is better, some parameters are not `uint256`

**Comment by hrharder** [comment]
lmk if this is the correct direction #131

**Comment by hrharder** [comment]
since you linked events for governance updates, I removed those in the PR's 2nd commit -- happy to re add if you like (seeing you did mention governance specifically in an above comment)

**Comment by fubuloubu** [comment]
@hrharder please keep them! I only added them to the Registry in that PR (still WIP), had not added them to the Vault yet.

Also, only have one event for when the transfer is accepted (e.g. `UpdateGovernance`), not when pending is set.

**Comment by fubuloubu** [comment]
Reviewed what you had so far, looking good!

**Comment by hrharder** [comment]
> @hrharder please keep them! I only added them to the Registry in that PR (still WIP), had not added them to the Vault yet.
> 
> Also, only have one event for when the transfer is accepted (e.g. `UpdateGovernance`), not when pending is set.

gotcha! no problem -- added [here](https://github.com/iearn-finance/yearn-vaults/pull/131/commits/641bdb2efce2a7a73a57a30f53a71c5e54fab3b4)
