### ISSUE TITLE
Avoid calling adjustPosition when there is not enough want

### ISSUE THREAD

**Issue by Macarse** [iearn-finance/yearn-vaults#129]
If the strategy doesn't have more `want` than `debtOutstanding` there is no need to call `adjustPosition`.

**Comment by fubuloubu** [comment]
Per discussion in #130, basically `adjustPosition`/`prepareReturn` should be able to handle a deficit condition (e.g. `want.balanceOf(address(this)) < _debtOutstanding`) without throwing, as it will prevent proper operation of `tend`/`harvest`. There are some scenarios where strategies need to take positive action on a deficit, such as a in time-bound or debt-based strategies, and it is not advisible to have `BaseStrategy` systematically avoid calling `adjustPosition` in `harvest` for efficiency/safety reasons.
