### ISSUE TITLE
Add Metadata URI to BaseStrategy/Strategy

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#165]
add a new public storage variable `metadataURI`, which can be edited by the strategist and governance, and contains a URI link to some publicly accessible CDN (such as IPFS e.g. `ipfs://Qm....`).

This link should be content-addressed if possible to avoid rewriting the content without an on-chain audit history.

The content itself should be JSON encoded, and list things such as a description of the Strategy, what tokens it involves, failure modes, etc.

Also consider replacing `Strategy.name()` with this field

**Comment by steffenix** [comment]
Never worked with ipfs, would live to try. Can I pick this issue?

**Comment by fubuloubu** [comment]
> Never worked with ipfs, would live to try. Can I pick this issue?

Sure! It's fairly easy change, basically add a new `string public metadataURI` to `BaseStrategy`, which would usually be set to something like `"ipfs://QmRsvEpJggeu4HhoafzRFobV4sbwVVTXMrdb2p8XWv7bCS"`
