### ISSUE TITLE
Add MiniMe-style Balance Checkpointing to Vault Shares

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#170]
Motivation:
- supports (multiple) claimable reward tokens for Vault shareholders
- supports Vault shares being used in governance (e.g. yvYFI)
- supports Vault recovery process (basically, an "Exit Strategy" that allows people to recover funds based on their balances at a particular block)
- supports being able to restrict withdrawals based on block height of deposits (hopefully can be used to solve sandwich attacks with a 24hr hold on deposits)

Example implementations:
- https://github.com/Giveth/minime/blob/master/contracts/MiniMeToken.sol
- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20Snapshot.sol
- https://github.com/iearn-finance/yearn-token/pull/1

**Comment by andy8052** [comment]
I can't assign myself to things but you can toss me on here. Working on this currently

**Comment by fameal** [comment]
@fubuloubu can we close it in favor of #167  ?

**Comment by fubuloubu** [comment]
yeah sure
