### ISSUE TITLE
Parametrize test suite on Tokens with different decimal values

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#220]
We support a number of different tokens using different decimal amounts (e.g. GUSD has 2, USDC has 6, wBTC has 8, etc.), but we only currently test with 18 decimals. So, we should parametrize our Tokens to try different values just to make sure our calculations are consistent enough not to cause problems.

Also need some test cases that ensure precision loss is bounded below some expected amount.

**Comment by steffenix** [comment]
will help
