### ISSUE TITLE
Deep withdrawals with slippage can cause a socialized loss

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#40]
Because withdrawals leave some underdefined behavior to strategies to implement them as "try to liquidate up to `amountNeeded` (see below)

https://github.com/iearn-finance/yearn-vaults/blob/22d0607291980bb19b5110c46440843b2d9e3938/contracts/BaseStrategy.sol#L276-L286

We end up in a scenario where large slippage could be caused by that action, but the withdrawer would not realize that loss and instead socialize it to the other depositors (see below)

https://github.com/iearn-finance/yearn-vaults/blob/22d0607291980bb19b5110c46440843b2d9e3938/contracts/Vault.vy#L432-L440

We currently mitigate this through Strategy review, but this is not ideal

**Comment by ShadeUndertree** [comment]
I'd like to pick this one up.

**Comment by fubuloubu** [comment]
Consider merging `liquidatePosition()` and `exitPosition()` as `exitPosition() := liquidatePosition(_debtOutstanding)`
