### ISSUE TITLE
Add Registry contract

### ISSUE THREAD

**Issue by lbertenasco** [iearn-finance/yearn-vaults#45]
> Work by submitting a PR to the [`feat/registry`](../tree/feat/registry) branch.

Contract is here: [`Registry.sol`](../blob/feat/registry/contracts/Registry.sol)

Let's continue [this discussion](https://github.com/iearn-finance/yearn-protocol/issues/58) on this issue.

**Comment by freightledger** [comment]
Is there a pattern for the value of `vault api version` i.e. a regex or some reference to versioning? 

E.g. v1.1.0 != v1.01.0 where 1.1.0 is actually 1.10.1?

**Comment by sambacha** [comment]
Is there a pattern for the value of `vault api version` i.e. a regex or some reference to versioning? 

E.g. v1.1.0 != v1.01.0 where 1.1.0 is actually 1.10.1?
