### ISSUE TITLE
Generate list of events 

### ISSUE THREAD

**Issue by milkyklim** [iearn-finance/yearn-vaults#6]
Current [subgraph](https://github.com/iearn-finance/yearn-subgraph/blob/master/schema.graphql) is ugly cause there is no standartized way to retrieve parameters. 

Filter which parameters are used/useful and introduce corresponding events.

**Comment by fubuloubu** [comment]
I think this can be closed with the addition of the Registry?

**Comment by dougstorm** [comment]
Agree this can be closed now that we have registry
