### ISSUE TITLE
Add Guest List

### ISSUE THREAD

**Issue by fubuloubu** [iearn-finance/yearn-vaults#71]
We might want to let Vaults to be able to define "guest lists", which would be another contract that dictates who is allowed to participate in a Vault (and transfer shares). Potential use case here might be for more "experimental" style Vaults, or for "high risk" Vaults where we might want to define a limit based on something like $ value of YFI staked in governance, etc.

This would look like the following:
```python
interface GuestList:
    def authorized(guest: address) -> bool: view

guestList: public(GuestList)


... # In deposit()
    if self.guestList.address != ZERO_ADDRESS:
         assert self.guestList.authorized(msg.sender)
...
```

**Comment by WrongNebula** [comment]
Can we have Bounc3rs at the gate too?

**Comment by ShadeUndertree** [comment]
I'd like to pick this one up.

**Comment by fubuloubu** [comment]
Note: add "deposit size" to authorization check, so we can do limits based on total wealth, or amount of YFI, or stuff like that, e.g.:
```python
interface GuestList:
    def authorized(guest: address, amount: uint256) -> bool: view

guestList: public(GuestList)


... # In deposit(_amount)
    if self.guestList.address != ZERO_ADDRESS:
         assert self.guestList.authorized(msg.sender, _amount)
...
```

**Comment by banteg** [comment]
I've implemented this concept here. A bouncer can maintain a guest list, as well as a list of tokens which guarantee entrance if a user holds a certain min amount of them.
https://github.com/banteg/guest-list/blob/master/contracts/GuestList.vy

**Comment by ShadeUndertree** [comment]
@banteg would you like me to take what you've written and add it to the v2 vaults, plus tests? Or should I move on to something else? (since your implementation seems pretty comprehensive, I'd just be copying & pasting and adding a few tests)

**Comment by fubuloubu** [comment]
For this feature, I'd say we add a "test guest list" that is just a simpler version of what @banteg implemented. His version can probably continue adding new features (maybe merkle tree claim check?)
