### ISSUE TITLE
Improve exitPosition logic

### ISSUE THREAD

**Issue by Macarse** [iearn-finance/yearn-vaults#99]
In 0.2.0, `exitPosition` was modified to be able to return a tuple with `(uint256 _loss, uint256 _debtPayment)`.
There are two issues which were not addressed:

a) `exitPosition` might be able to return a profit
b) `exitPosition` is also called from `setEmergencyExit()` but the return values are not read by the vault.

Since after `setEmergencyExit()`, the strategist needs to call `harvest()`, I propose:

a) Remove the call to `exitPosition()` in `setEmergencyExit()`
b) Change the logic in harvest to handle to do the following:

```
if (emergencyExit) {
  (profit, loss, debtPayment) = exitPosition(vault.debtOutstanding());
} else {
  (profit, loss, debtPayment) = prepareReturn(vault.debtOutstanding());
}
```

Simple strategies which can withdraw immediately can call `prepareReturn` inside `exitPosition` and more complex strategies can try to unwind faster.

**Comment by fubuloubu** [comment]
heh, I wonder if this would work:
```solidity
(profit, loss, debtPayment) = 
    emergencyExit
    ? exitPosition(vault.debtOutstanding())
    : prepareReturn(vault.debtOutstanding());
```
